### ISSUE TITLE
Docker version tags

### ISSUE THREAD

**Issue by vincer** [victorcoder/docker-dkron#4] opened 2016-11-29 19:57 UTC
It would be useful for deployment reasons to start tagging images in Docker Hub.

Each release gets its own tag (0.9.1 release would get a "0.9.1" tag)
Every major and minor version would get a version tag in the standard "docker" way. (tag "0.9" would point to the latest 0.9.x release)

**Comment by vcastellm** [comment] 2016-12-06 23:07
Duplicate of https://github.com/victorcoder/dkron/issues/211

**Closed as completed by vcastellm** 2016-12-06 23:07 UTC
